spring:
    application:
        name: agrasset-center

server:
    port: 8761 #启动端口

eureka: 
   server: 
      enable-self-preservation: false #设为false，关闭自我保护
      eviction-interval-timer-in-ms: 4000 #单位毫秒，默认是60*1000
      renewalPercentThreshold: 0.49
      
   client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        
